<?php
return [
    'active_ecommerce_african_payment_add_on' =>'Halovi eCommerce African Payment Gateway add-on',
    'bundle' => 'Bundle of African Payment Method for Halovi eCommerce CMS',
    'check_demo' => 'Check Demo',
    'check_pricing' => 'Check Pricing',
    'requirements' => 'Requirements',
    'active_ecommerce_cms' => 'only available For <span style="color: #e43d04"><strong>Halovi eCommerce CMS</strong>',
    'minium_version' => '[ M I N I M U M  V E R S I O N  :  3 . 7 ]',
    'minimum_php_version' => 'Minimum PHP version : ',
    'minimum_mysql_version' => 'Minimum MySQL version : ',
    'african_payment_gateway_system' => '<strong><span style="color: #326333">African Payment</span> Gateway</strong> <span style="color: #326333"><strong>System</strong></span>',
    'config_page_easily' => 'Config Page Easily',
    'african_payment_gateway_in_checkout' => 'African Payment Gateway in Checkout',
    'african_payment_in_wallet_recharge'=>'African Payment in Wallet Recharge',
    'how_it_works' => 'How it Works?',
    'african_payment_gateway' => '<span style="color: #575a63">Configure <span style="color: #326333">African Payment gateway</span> payment method with Proper Credentials</span>',
    'customers_will_get_payment'=>'<span style="color: #575a63"> Customers will get <span style="color: #326333">payment</span> option during checkout</span>',
    'customers_will_get_african_payment_gateway' => '<span style="color: #575a63">Customers will get <span style="color: #326333">African Payment gateway</span> payment options during wallet recharge</span>',
    'pricing' => 'Pricing',
    'money_regular_licence_title' => '$25',
    'regular_licence_title'=>'REGULAR LICENSE',
    'regular_licence_content1'=>'LIFETIME UPDATE',
    'regular_licence_content2'=>'PERMITTED FOR 1 DOMAIN',
    'regular_licence_content3'=>'6 MONTHS TECHNICAL SUPPORT',
    'regular_licence_content4'=>'ZENDESK SUPPORT (1 BUSINESS DAY)',
    'regular_licence_content5'=>'LIVE SUPPORT (ANYDESK)',
    'regular_licence_content6'=>'FREE INSTALLATION',
    'regular_licence_content7'=>'PERMITTED FOR CUSTOMIZATION',
    'regular_licence_content8'=>'FREE 3RD PARTY CONFIGURATIONS',
    'purchase_regular_license' => 'Purchase Regular license',
    'extended_license_title' => 'EXTENDED LICENSE',
    'money_extended_license_title' => '$150',
    'extended_license_content1' => 'LIFETIME UPDATE',
    'extended_license_content2' => 'PERMITTED FOR 1 DOMAIN',
    'extended_license_content3' => '6 MONTHS TECHNICAL SUPPORT',
    'extended_license_content4' => 'ZENDESK SUPPORT (1 BUSINESS DAY)',
    'extended_license_content5' => 'LIVE SUPPORT (ANYDESK)',
    'extended_license_content6' => 'FREE INSTALLATION',
    'extended_license_content7' => 'PERMITTED FOR CUSTOMIZATION',
    'extended_license_content8' => 'FREE 3RD PARTY CONFIGURATIONS',
    'purchase_extended_license' => 'Purchase Extended License',

    ];
